'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { encryptData } from '@/lib/encryption';
import { motion, AnimatePresence } from 'framer-motion';
import { QRCodeSVG } from 'qrcode.react';

export default function SetupWizard() {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [jwt, setJwt] = useState('');
  const [gatewayUp, setGatewayUp] = useState(false);
  const [keys, setKeys] = useState({ openai: '', anthropic: '', elevenlabs: '' });

  useEffect(() => {
    // Step 1: Gateway Auto-detection
    if (step === 1) {
      const checkGateway = async () => {
        try {
          const res = await fetch('http://localhost:4000/health');
          if (res.ok) setGatewayUp(true);
        } catch {
          setGatewayUp(false);
        }
      };
      const interval = setInterval(checkGateway, 2000);
      return () => clearInterval(interval);
    }
  }, [step]);

  const handleNext = async () => {
    if (step === 1) {
      if (!jwt.trim()) return alert('Please scan or paste the device JWT.');
      localStorage.setItem('clawshield_device_jwt', jwt);
      setStep(2);
    } else if (step === 2) {
      // Encrypt and store API keys locally
      const storedJwt = localStorage.getItem('clawshield_device_jwt')!;
      const encryptedStr = await encryptData(JSON.stringify(keys), storedJwt);
      localStorage.setItem('clawshield_api_configs', encryptedStr);
      setStep(3);
    } else if (step === 3) {
      setStep(4);
    } else {
      router.push('/dashboard');
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-background p-4">
      <div className="w-full max-w-lg rounded-xl border bg-card p-8 shadow-lg">
        <div className="mb-8 flex items-center justify-center gap-2">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary text-primary-foreground font-bold">
            CS
          </div>
          <h1 className="text-2xl font-bold tracking-tight">ClawShield Setup</h1>
        </div>

        <AnimatePresence mode="wait">
          {step === 1 && (
            <motion.div
              key="step1"
              initial={{ x: 20, opacity: 0 }}
              animate={{ x: 0, opacity: 1 }}
              exit={{ x: -20, opacity: 0 }}
              className="space-y-4"
            >
              <h2 className="text-xl font-semibold">1. Pair your hardware</h2>
              <div className="flex flex-col items-center gap-4">
                {gatewayUp ? (
                  <div className="bg-green-100 text-green-700 px-4 py-2 rounded-full text-sm font-medium">
                    ✔ Gateway Detected
                  </div>
                ) : (
                  <div className="bg-yellow-100 text-yellow-700 px-4 py-2 rounded-full text-sm font-medium animate-pulse">
                    Searching for local gateway...
                  </div>
                )}

                {jwt && (
                  <div className="p-4 bg-white rounded-lg shadow-sm">
                    <QRCodeSVG value={JSON.stringify({ gatewayUrl: 'http://localhost:4000', token: jwt })} />
                    <p className="text-[10px] text-center mt-2 text-muted-foreground">Scan with mobile dashboard</p>
                  </div>
                )}
              </div>
              <p className="text-sm text-muted-foreground text-center">
                Paste the hardware JWT generated by your agent console.
              </p>
              <textarea
                className="w-full rounded-md border bg-input px-3 py-2 text-sm font-mono placeholder:text-muted focus:outline-none focus:ring-2 focus:ring-ring min-h-[100px]"
                placeholder="eyJhbGciOiJIUz..."
                value={jwt}
                onChange={(e) => setJwt(e.target.value)}
              />
            </motion.div>
          )}

          {step === 2 && (
            <motion.div
              key="step2"
              initial={{ x: 20, opacity: 0 }}
              animate={{ x: 0, opacity: 1 }}
              exit={{ x: -20, opacity: 0 }}
              className="space-y-4"
            >
              <h2 className="text-xl font-semibold">2. Provide AI Models</h2>
              <p className="text-sm text-muted-foreground">
                These are encrypted and stored solely on your device.
              </p>
              <div className="space-y-3">
                <input
                  type="password"
                  placeholder="Anthropic API Key (Required for Agent)"
                  className="w-full rounded-md border bg-input px-3 py-2"
                  value={keys.anthropic}
                  onChange={(e) => setKeys({ ...keys, anthropic: e.target.value })}
                />
                <input
                  type="password"
                  placeholder="OpenAI API Key (Optional Whisper fallback)"
                  className="w-full rounded-md border bg-input px-3 py-2"
                  value={keys.openai}
                  onChange={(e) => setKeys({ ...keys, openai: e.target.value })}
                />
                <input
                  type="password"
                  placeholder="ElevenLabs API Key (For TTS)"
                  className="w-full rounded-md border bg-input px-3 py-2"
                  value={keys.elevenlabs}
                  onChange={(e) => setKeys({ ...keys, elevenlabs: e.target.value })}
                />
              </div>
            </motion.div>
          )}

          {step === 3 && (
            <motion.div
              key="step3"
              initial={{ x: 20, opacity: 0 }}
              animate={{ x: 0, opacity: 1 }}
              exit={{ x: -20, opacity: 0 }}
              className="space-y-4 text-center"
            >
              <h2 className="text-xl font-semibold">3. Hardware Verification</h2>
              <div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full border-4 border-primary/20 bg-primary/10">
                <span className="text-4xl">🎤</span>
              </div>
              <p className="text-sm text-muted-foreground">
                Microphone hardware detected and ready.
              </p>
            </motion.div>
          )}

          {step === 4 && (
            <motion.div
              key="step4"
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              className="space-y-4 text-center"
            >
              <h2 className="text-xl font-semibold">You're all set!</h2>
              <p className="text-sm text-muted-foreground">
                Your zero-terminal agent is live and sandboxed.
              </p>
              <div className="flex justify-center pt-4">
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ type: 'spring', stiffness: 260, damping: 20 }}
                  className="h-16 w-16 rounded-full bg-green-500 shadow-[0_0_30px_#22c55e]"
                />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="mt-8 flex justify-end">
          <button
            onClick={handleNext}
            className="rounded-md bg-primary px-6 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors"
          >
            {step === 4 ? 'Enter Dashboard' : 'Next Step'}
          </button>
        </div>
      </div>
    </div>
  );
}
